version: '3.7'

services:
  db:
    image: mariadb:10.4
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: humhub
      MYSQL_USER:     humhub
      MYSQL_PASSWORD: password
    expose:
      - "3306"
    volumes:
      - ${PWD}/volumes/db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile.rel
    restart: always
    volumes:
      - ${PWD}/humhub:/var/www/html
    ports:
      - 80:80
